#!/usr/bin/env python3

import imported

# The mp module will alter the builtin - this should affect all future calls to the builtin `open`,
# regardless if they are initially referred to in modules that are imported earlier or later.

import _mp

import imported_later


def main():
    try:
        with open("/tmp/x", "r"):
            pass
    except IOError as e:
        print(e)
    with open("/tmp/y", "w") as f:
        f.writelines(["hello", " ", "world"])
    with open("/tmp/y", "r") as f:
        print(f.read())

    with imported.foo("/tmp/y", "r") as f:
        print(f.read())

    imported_later.bar()
    with imported.foo("/tmp/z", "r") as f:
        print(f.read())


if __name__ == '__main__':
    main()
